name = "short-link"
type = "javascript"

account_id = "39a7ded207d46b8e258ee9ee2edee52a"
workers_dev = true
webpack_config = "webpack.config.js"

kv_namespaces = [
  { binding = "PB", id = "a4b5e2d509794666b1d515e940159475" },
]

[build]
command = "yarn install && yarn build"

[build.upload]
format = "service-worker"
